# Generated by Django 4.2.25 on 2025-10-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='motor_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
