# Generated by Django 4.2.24 on 2025-09-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_slot", models.CharField(max_length=10)),
                ("stripe_session_id", models.CharField(max_length=255)),
                ("paid", models.BooleanField(default=False)),
            ],
        ),
    ]
