# Generated by Django 4.2.11 on 2025-10-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_refundmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refundmodel",
            name="stripe_refund_id",
        ),
        migrations.AddField(
            model_name="refundmodel",
            name="refunded",
            field=models.BooleanField(default=False),
        ),
    ]
