# Generated by Django 4.2.11 on 2025-10-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_remove_refundmodel_stripe_refund_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmodel",
            name="amount",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
