# Generated by Django 4.2.11 on 2025-10-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_paymentmodel_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmodel",
            name="test",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="refundmodel",
            name="test",
            field=models.BooleanField(default=True),
        ),
    ]
