# Generated by Django 4.2.11 on 2025-10-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_paymentmodel_test_refundmodel_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmodel",
            name="most_recent_intent",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
