# Generated by Django 4.2.11 on 2025-10-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_paymentmodel_most_recent_intent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmodel",
            name="amount",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="product_slot",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
