"""
Django settings for VendOS project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from corsheaders.defaults import default_headers
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-395g4l$d4l+mhj*9znr$zasbqf#_kdph@2+-375)jfpf@apxi="

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['sympodial-plicately-fredia.ngrok-free.dev', "127.0.0.1", "localhost"]

DISPENSE_TIME = 5  # seconds


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "tests.apps.TestsConfig",
    "main.apps.MainConfig",
    "payments.apps.PaymentsConfig",
    "status.apps.StatusConfig",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "VendOS.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "main.context_processors.debug_flag",
            ],
        },
    },
]

WSGI_APPLICATION = "VendOS.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# settings.py

CORS_ALLOWED_ORIGINS = [
    "https://www.ds-technical-solutions.nl", ]

CORS_ALLOW_HEADERS = list(default_headers) + [
    "ngrok-skip-browser-warning",
]

CORS_ALLOW_CREDENTIALS = True

# Explicitly allow the methods you use
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "OPTIONS",
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR/'VendOS', 'static')
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Webhook ID stripe 
STRIPE_WH_ID_TEST = "we_1SBiAMEqCs85vuphxxE5NnCG" # Change to your actual webhook ID
STRIPE_WH_ID_LIVE = "we_1SBgrYEqCs85vuphWbnETcjZ"
# Stripe env variables 
STRIPE_PK_TEST = os.getenv("STRIPE_PK_TEST")
STRIPE_PK_LIVE = os.getenv("STRIPE_PK_LIVE")
STRIPE_SK_TEST = os.getenv("STRIPE_SK_TEST")
STRIPE_SK_LIVE = os.getenv("STRIPE_SK_LIVE")
STRIPE_WH_SECRET = os.getenv("STRIPE_ENDPOINT")

NGROK_SEC = os.getenv("NGROK_SEC")
NGROK_TEST = os.getenv("NGROK_TEST")
STRIPE_PAYMENT_LINK = "https://buy.stripe.com/14A5kD0g20Rd8Kd4iNfUQ00" # Move to env variable?