# Generated by Django 4.2.24 on 2025-10-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="errored",
            field=models.BooleanField(default=False),
        ),
    ]
